name: giflute
description: A Flutter ChatGPT-like application using GigaChat API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_markdown: ^0.6.17
  google_fonts: ^5.1.0
  uuid: ^4.0.0
  dio: ^5.4.1
  markdown: ^7.3.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.0.0
  flutter_tts: ^4.0.0
  flutter_sound: ^9.27.0
  just_audio: ^0.9.36
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 